"""add forecast columns to market_prices

Revision ID: 3221ec14e2e6
Revises: caa7e413e358
Create Date: 2026-06-11 13:15:37.224829
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3221ec14e2e6'
down_revision: str | None = 'caa7e413e358'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_flocks_previous_formulation_id_formulations', 'flocks', 'formulations', ['previous_formulation_id'], ['formulation_id'], ondelete='SET NULL', use_alter=True)
    op.add_column('market_prices', sa.Column('is_forecast', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('market_prices', sa.Column('forecast_model', sa.String(length=60), nullable=True))
    op.create_index('ix_market_prices_forecast', 'market_prices', ['ingredient_id', 'is_forecast'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_prices_forecast', table_name='market_prices')
    op.drop_column('market_prices', 'forecast_model')
    op.drop_column('market_prices', 'is_forecast')
    op.drop_constraint('fk_flocks_previous_formulation_id_formulations', 'flocks', type_='foreignkey')
    # ### end Alembic commands ###
