"""initial schema

Revision ID: caa7e413e358
Revises: 
Create Date: 2026-06-10 08:12:46.814340
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'caa7e413e358'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('name', name=op.f('uq_ingredients_name'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('flocks',
    sa.Column('flock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('current_age_weeks', sa.Integer(), nullable=False),
    sa.Column('flock_size', sa.Integer(), nullable=False),
    sa.Column('previous_formulation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_formulation_id'], ['formulations.formulation_id'], name='fk_flocks_previous_formulation_id_formulations', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_flocks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flock_id', name=op.f('pk_flocks'))
    )
    op.create_index(op.f('ix_flocks_user_id'), 'flocks', ['user_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('price_per_kg_rwf', sa.Float(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('market_location', sa.String(length=80), nullable=False),
    sa.Column('entered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.user_id'], name=op.f('fk_market_prices_entered_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('fk_market_prices_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_id', name=op.f('pk_market_prices'))
    )
    op.create_index('ix_market_prices_ingredient_date', 'market_prices', ['ingredient_id', 'price_date'], unique=False)
    op.create_table('nutritional_compositions',
    sa.Column('comp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_type', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('analysis_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('fk_nutritional_compositions_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comp_id', name=op.f('pk_nutritional_compositions'))
    )
    op.create_index(op.f('ix_nutritional_compositions_ingredient_id'), 'nutritional_compositions', ['ingredient_id'], unique=False)
    op.create_table('formulations',
    sa.Column('formulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flock_id', sa.Integer(), nullable=False),
    sa.Column('total_cost_per_kg_rwf', sa.Float(), nullable=False),
    sa.Column('dtsi_score', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.Enum('NSGA_II', 'LP', name='formulation_method'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.flock_id'], name=op.f('fk_formulations_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('formulation_id', name=op.f('pk_formulations'))
    )
    op.create_index(op.f('ix_formulations_flock_id'), 'formulations', ['flock_id'], unique=False)
    op.create_table('formulation_ingredients',
    sa.Column('formulation_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('proportion_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.formulation_id'], name=op.f('fk_formulation_ingredients_formulation_id_formulations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], name=op.f('fk_formulation_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('formulation_id', 'ingredient_id', name=op.f('pk_formulation_ingredients'))
    )
    op.create_table('formulation_price_snapshots',
    sa.Column('formulation_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulation_id'], ['formulations.formulation_id'], name=op.f('fk_formulation_price_snapshots_formulation_id_formulations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['market_prices.price_id'], name=op.f('fk_formulation_price_snapshots_price_id_market_prices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('formulation_id', 'price_id', name=op.f('pk_formulation_price_snapshots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formulation_price_snapshots')
    op.drop_table('formulation_ingredients')
    op.drop_index(op.f('ix_formulations_flock_id'), table_name='formulations')
    op.drop_table('formulations')
    op.drop_index(op.f('ix_nutritional_compositions_ingredient_id'), table_name='nutritional_compositions')
    op.drop_table('nutritional_compositions')
    op.drop_index('ix_market_prices_ingredient_date', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_flocks_user_id'), table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
