import 'package:flutter/material.dart';
import '../theme.dart';
import '../widgets/ui.dart';

class LegalPrivacyScreen extends StatelessWidget {
  final int initialTab;

  const LegalPrivacyScreen({super.key, this.initialTab = 0});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      initialIndex: initialTab,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Legal & Privacy Policy'),
          bottom: const TabBar(
            tabs: [
              Tab(icon: Icon(Icons.gavel_outlined), text: 'EULA & Terms'),
              Tab(icon: Icon(Icons.privacy_tip_outlined), text: 'Privacy Policy'),
            ],
          ),
        ),
        body: const TabBarView(
          children: [
            _EulaTabView(),
            _PrivacyTabView(),
          ],
        ),
      ),
    );
  }
}

class _EulaTabView extends StatelessWidget {
  const _EulaTabView();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        AppCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(10),
                    decoration: BoxDecoration(
                      color: AppColors.seed.withValues(alpha: 0.12),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Icon(Icons.gavel, color: AppColors.seed, size: 24),
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('End-User License Agreement',
                            style: theme.textTheme.titleMedium
                                ?.copyWith(fontWeight: FontWeight.bold)),
                        const SizedBox(height: 2),
                        Text('Version 1.0 • Effective July 2026',
                            style: theme.textTheme.bodySmall?.copyWith(
                                color: scheme.onSurfaceVariant)),
                      ],
                    ),
                  ),
                ],
              ),
              const Divider(height: 24),
              Text(
                'Please read this End-User License Agreement ("EULA") carefully before using the Dynamic Feed Formulator application. By creating an account or using the app, you agree to be bound by these terms.',
                style: theme.textTheme.bodyMedium?.copyWith(height: 1.4),
              ),
            ],
          ),
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.health_and_safety_outlined,
          badgeColor: Colors.amber,
          title: 'Clause 1: Algorithmic Disclaimer & Biological Advisory',
          content:
              'Automated formulations generated by the Multi-Objective Evolutionary Solver (NSGA-II) serve strictly as animal nutrition guidelines based on NRC (1994) standards and regional price dynamics.\n\n'
              '• Formulations do NOT replace professional veterinary diagnosis, vaccination, or disease treatment.\n'
              '• Farmers are advised to inspect feed ingredient quality (e.g., moisture, aflatoxin levels) prior to batch mixing.\n'
              '• Software developers and African Leadership University assume no liability for biological flock losses, disease outbreaks, or unverified farm management practices.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.analytics_outlined,
          badgeColor: Colors.blue,
          title: 'Clause 2: Open Data Provenance & Forecasting Transparency',
          content:
              'Market price trends and historical data are harvested from public datasets published by the World Food Programme (WFP) and Rwanda Agriculture Board (RAB).\n\n'
              '• Machine learning price forecasts (Gradient Boosting Regressor) carry an empirical error margin (2.52% MAPE).\n'
              '• Predictions represent statistical estimates based on historical returns and seasonal patterns; actual retail market prices may vary due to localized market events.\n'
              '• Imported micro-ingredients (premixes, synthetic amino acids) rely on manual price overrides when regional price histories are unavailable.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.verified_user_outlined,
          badgeColor: Colors.green,
          title: 'Clause 3: Grant of License & Acceptable Use',
          content:
              'You are granted a non-exclusive, non-transferable, revocable license to use the application for individual or commercial poultry flock feed management.\n\n'
              'You agree NOT to:\n'
              '• Reverse engineer, decompile, or extract the core optimization solver source code for commercial resale.\n'
              '• Attempt to inject malicious data into public price submission endpoints.\n'
              '• Use telemetry data for market price manipulation or predatory grain trading.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.assignment_late_outlined,
          badgeColor: Colors.purple,
          title: 'Clause 4: Limitation of Liability',
          content:
              'To the maximum extent permitted by applicable law in Rwanda, the application is provided "AS IS" without warranties of any kind.\n\n'
              'In no event shall the authors, university, or contributors be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this software.',
        ),
        const SizedBox(height: 24),
      ],
    );
  }
}

class _PrivacyTabView extends StatelessWidget {
  const _PrivacyTabView();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        AppCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(10),
                    decoration: BoxDecoration(
                      color: Colors.teal.withValues(alpha: 0.12),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Icon(Icons.shield, color: Colors.teal, size: 24),
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Privacy Policy & Data Rights',
                            style: theme.textTheme.titleMedium
                                ?.copyWith(fontWeight: FontWeight.bold)),
                        const SizedBox(height: 2),
                        Text('Compliant with Rwanda Law N° 058/2021',
                            style: theme.textTheme.bodySmall?.copyWith(
                                color: scheme.onSurfaceVariant)),
                      ],
                    ),
                  ),
                ],
              ),
              const Divider(height: 24),
              Text(
                'We respect your privacy and are committed to protecting personal data collected through our application in compliance with Rwanda Law N° 058/2021 on Personal Data Protection and Privacy.',
                style: theme.textTheme.bodyMedium?.copyWith(height: 1.4),
              ),
            ],
          ),
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.location_off_outlined,
          badgeColor: Colors.teal,
          title: 'Clause 1: Data Minimization & Location Privacy',
          content:
              'We collect only the minimal information necessary to deliver formulation services:\n\n'
              '• Farm locations are stored strictly as coarse market region strings ("Province / District / Market"), NEVER as precise GPS coordinates.\n'
              '• Account details (full name, email, role) are encrypted.\n'
              '• Location sanitization prevents regional feed syndicates from exploiting farm telemetry for price gouging.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.storage_outlined,
          badgeColor: Colors.indigo,
          title: 'Clause 2: Offline Data Ownership & Local Storage Rights',
          content:
              'All cached recipes, flock profiles, and formulation history stored on your device remain your sole property.\n\n'
              '• Local database storage (SQLite) allows full offline application functionality without network connectivity.\n'
              '• You retain full rights to export your data to open formats (PDF, CSV) at any time without vendor lock-in.\n'
              '• Local data can be cleared at any time via Account settings.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.lock_clock_outlined,
          badgeColor: Colors.blueGrey,
          title: 'Clause 3: Security & Data Encryption Standards',
          content:
              'We implement state-of-the-art security measures to safeguard user data:\n\n'
              '• All network communication uses TLS 1.3 encryption.\n'
              '• Passwords are hashed using Bcrypt (work factor 12).\n'
              '• API authentication utilizes short-lived JWT tokens (30-minute expiration).\n'
              '• The database operates in an isolated container network.',
        ),
        const SizedBox(height: 14),

        const _LegalSectionCard(
          icon: Icons.account_balance_outlined,
          badgeColor: Colors.deepOrange,
          title: 'Clause 4: Data Rights under Rwanda Law N° 058/2021',
          content:
              'Under Article 3 and related provisions of Rwanda Law N° 058/2021, you possess the following rights:\n\n'
              '• Right to access your stored personal data.\n'
              '• Right to rectify inaccurate or incomplete records.\n'
              '• Right to request erasure of your account and associated telemetry.\n'
              '• Right to withdraw consent for optional data processing.',
        ),
        const SizedBox(height: 24),
      ],
    );
  }
}

class _LegalSectionCard extends StatelessWidget {
  final IconData icon;
  final Color badgeColor;
  final String title;
  final String content;

  const _LegalSectionCard({
    required this.icon,
    required this.badgeColor,
    required this.title,
    required this.content,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AppCard(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: badgeColor, size: 22),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  title,
                  style: theme.textTheme.titleSmall
                      ?.copyWith(fontWeight: FontWeight.bold),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(
            content,
            style: theme.textTheme.bodyMedium
                ?.copyWith(height: 1.45, color: theme.colorScheme.onSurface),
          ),
        ],
      ),
    );
  }
}
